version: "3"      

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                           C O D E I G N I T E R                          #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    pedale_douce:
        build: .
        image: pedaledouce_atsanna/ci4
        container_name: 'pedale_douce'
        ports:
          - 80:80
        links:
          - pedale_douce_mysql
        volumes:
          - ./www:/var/www/html

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                                 M Y S Q L                                #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
    pedale_douce_mysql:
        image: mariadb:10.5.5
        container_name: 'pedale_douce_mysql'
        ports:
          - 3306:3306
        volumes:
          - ./mysql:/var/lib/mysql
          - ./logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: pedale_douce
          MYSQL_DATABASE: pedale_douce
          MYSQL_USER: pedale_douce
          MYSQL_PASSWORD: pedale_douce

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                            P H P M Y A D M I N                           #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#             
    pedale_douce_phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: 'pedale_douce_phpmyadmin'
        links:
          - pedale_douce_mysql
        environment:
          PMA_HOST: pedale_douce_mysql
          PMA_PORT: 3306
        ports:
          - 81:80
        volumes:
          - ./sessions:/sessions

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
